import pandas as pd
from datetime import date

def formatCust(data, path):
    data = data.drop_duplicates(subset = ['address'])
    custData = pd.DataFrame({'title':'',
                             'Company':'',
                             'First Name': data['firstname'].tolist(),
                             'Middle Name':'',
                             'Last Name': data['lastname'].tolist(),
                             'Suffix':'',
                             'Display Name As':data['fullname'].tolist(),
                             'Print On Check As':'',
                             'Billing Address Line 1':data['address'],
                             'Billing Address Line 2':'',
                             'Billing Address Line 3':'',
                             'Billing Address City':data['city'],
                             'Billing Address Postal Code':data['zip'],
                             'Billing Address Country':data['country'],
                             'Billing Address State':data['state'],
                             'Shipping Address Line 1':data['address'],
                             'Shipping Address Line 2':'',
                             'Shipping Address Line 3':'',
                             'Shipping Address City':data['city'],
                             'Shipping Address Postal Code':data['zip'],
                             'Shipping Address Country':data['country'],
                             'Shipping Address State':data['state'],
                             'Phone':'',
                             'Mobile':'',
                             'Fax':'',
                             'Other':'',
                             'Website':'',
                             'Email':'',
                             'Terms':'',
                             'Preferred Payment Method':'',
                             'Tax Resale No':'',
                             'Preferred Delivery Method':'',
                             'Bill With Parent':'',
                             'Parent Customer':'',
                             'Opening Balance':'',
                             'Open Balance Date':'',
                             'Notes':'',
                             'Customer Taxable':'',
                             'Currency Code':''})
    custData.to_excel(path + 'CustUpload.xlsx', index = False, header = True)

def formatInvoice(data, path):
    today = date.today()
    today = today.strftime('%m/%d/%Y')
    invoiceData = pd.DataFrame({'Invoice No':'WN-'+data['orderNum'],
                                'Customer':data['fullname'],
                                'Invoice Date':today,
                                'Due Date':today,
                                'Shipping Date':today,
                                'Ship Via':'USPS',
                                'Tracking no':data['tracking'],
                                'Terms':'Prepaid',
                                'Billing Address Line 1':data['fullname'],
                                'Billing Address Line 2':data['address'],
                                'Billing Address Line 3':'',
                                'Billing Address City':data['city'],
                                'Billing Address Postal Code':data['zip'],
                                'Billing Address Country':data['country'],
                                'Billing Address State':data['state'],
                                'Shipping Address Line 1':data['fullname'],
                                'Shipping Address Line 2':data['address'],
                                'Shipping Address Line 3':'',
                                'Shipping Address City':data['city'],
                                'Shipping Address Postal Code':data['zip'],
                                'Shipping Address Country':data['country'],
                                'Shipping Address State':data['state'],
                                'Memo':'',
                                'Message displayed on invoice':'',
                                'Email':'',
                                'Shipping':'',
                                'Sales Tax Code':'',
                                'Sales Tax Amount':'',
                                'Discount Amount':'',
                                'Discount Percent':'',
                                'Discount Account':'',
                                'Apply Tax After Discount':'False',
                                'Service Date':'',
                                'Product/Service':data['brand'],
                                'Product/Service Description':data['description'],
                                'Product/Service Quantity':'1',
                                'Product/Service Rate':data['price'],
                                'Product/Service Amount':data['price'],
                                'Product/Service Taxable':'False',
                                'Product/Service Class':'',
                                'Show Sub Total':'',
                                'Deposit':'',
                                'Location':'',
                                'Custom Field Value (1)':'',
                                'Custom Field Value (2)':'',
                                'Custom Field Value (3)':'',
                                'Currency Code':'USD',
                                'Exchange Rate':'',
                                'Print Status':'True',
                                'Email Status':'False'})

    notes = pd.DataFrame({'Invoice No':'WN-'+data['orderNum'],
                                'Customer':'',
                                'Invoice Date':'',
                                'Due Date':'',
                                'Shipping Date':'',
                                'Ship Via':'',
                                'Tracking no':'',
                                'Terms':'Prepaid',
                                'Billing Address Line 1':'',
                                'Billing Address Line 2':'',
                                'Billing Address Line 3':'',
                                'Billing Address City':'',
                                'Billing Address Postal Code':'',
                                'Billing Address Country':'',
                                'Billing Address State':'',
                                'Shipping Address Line 1':'',
                                'Shipping Address Line 2':'',
                                'Shipping Address Line 3':'',
                                'Shipping Address City':'',
                                'Shipping Address Postal Code':'',
                                'Shipping Address Country':'',
                                'Shipping Address State':'',
                                'Memo':'',
                                'Message displayed on invoice':'',
                                'Email':'',
                                'Shipping':'',
                                'Sales Tax Code':'',
                                'Sales Tax Amount':'',
                                'Discount Amount':'',
                                'Discount Percent':'',
                                'Discount Account':'',
                                'Apply Tax After Discount':'False',
                                'Service Date':'',
                                'Product/Service':'',
                                'Product/Service Description':'Plus whatnot sales tax and shipping fee not accounted by WatchShopping',
                                'Product/Service Quantity':'',
                                'Product/Service Rate':'',
                                'Product/Service Amount':'',
                                'Product/Service Taxable':'False',
                                'Product/Service Class':'',
                                'Show Sub Total':'',
                                'Deposit':'',
                                'Location':'',
                                'Custom Field Value (1)':'',
                                'Custom Field Value (2)':'',
                                'Custom Field Value (3)':'',
                                'Currency Code':'USD',
                                'Exchange Rate':'',
                                'Print Status':'True',
                                'Email Status':'False'})

    #invoiceData = invoiceData.append(notes, ignore_index = True)
    invoiceData = pd.concat([invoiceData, notes])
    invoiceData.to_excel(path + 'InvoiceUpload.xlsx', index = False, header = True)
